# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_exampleseducationheaderorlist1text_exampleseducationheaderorlist2text_exampleseducationheaderorlist3'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksHeaderorList1Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(db_index=True, help_text='Порядковый номер заголовка h1 на странице', unique=True, verbose_name='Порядковый номер заголовка h1 на странице')),
                ('text', models.CharField(blank=True, help_text='Заголовки (h1) для страницы', max_length=255, verbose_name='Заголовки (h1) для страницы')),
            ],
        ),
        migrations.CreateModel(
            name='WorksHeaderorList2Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(db_index=True, help_text='Порядковый номер заголовка h2 на странице', unique=True, verbose_name='Порядковый номер заголовка h2 на странице')),
                ('text', models.CharField(blank=True, help_text='Заголовки (h2) для страницы', max_length=255, verbose_name='Заголовки (h2) для страницы')),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.WorksHeaderorList1Text')),
            ],
        ),
        migrations.CreateModel(
            name='WorksHeaderorList3Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(db_index=True, help_text='Порядковый номер заголовка h3 на странице', unique=True, verbose_name='Порядковый номер заголовка h3 на странице')),
                ('text', models.CharField(blank=True, help_text='Заголовки (h3) для страницы', max_length=255, verbose_name='Заголовки (h3) для страницы')),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.WorksHeaderorList2Text')),
            ],
        ),
        migrations.CreateModel(
            name='WorksHeaderorList4Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(db_index=True, help_text='Порядковый номер заголовка h4 на странице', unique=True, verbose_name='Порядковый номер заголовка h4 на странице')),
                ('text', models.CharField(blank=True, help_text='Заголовки (h4) для страницы', max_length=255, verbose_name='Заголовки (h4) для страницы')),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.WorksHeaderorList3Text')),
            ],
        ),
        migrations.CreateModel(
            name='WorksText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(db_index=True, help_text='Порядковый номер абзаца в тексте', unique=True, verbose_name='Порядковый номер абзаца в тексте')),
                ('text', models.TextField(help_text='Текст абзаца', verbose_name='Текст абзаца')),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.WorksHeaderorList4Text')),
            ],
        ),
        migrations.RenameModel(
            old_name='ExamplesEducationHeaderorList1Text',
            new_name='EducationHeaderorList1Text',
        ),
        migrations.RenameModel(
            old_name='ExamplesEducationHeaderorList2Text',
            new_name='EducationHeaderorList2Text',
        ),
        migrations.RenameModel(
            old_name='ExamplesEducationHeaderorList3Text',
            new_name='EducationHeaderorList3Text',
        ),
        migrations.RenameModel(
            old_name='ExamplesEducationHeaderorList4Text',
            new_name='EducationHeaderorList4Text',
        ),
        migrations.RenameModel(
            old_name='ExamplesEducationText',
            new_name='EducationText',
        ),
    ]
