# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_auto_20170502_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplesPython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(db_index=True, help_text='Порядковый номер объекта на странице', unique=True, verbose_name='Порядковый номер объекта на странице')),
                ('name_project', models.CharField(help_text='Название проекта', max_length=255, verbose_name='Название проекта')),
                ('bimage', models.ImageField(blank=True, upload_to='examples_python_images/', verbose_name='Картинка проекта')),
                ('net_address', models.CharField(blank=True, help_text='Ссылка на проект в сети', max_length=255, verbose_name='Ссылка на проект в сети')),
                ('git_address', models.CharField(help_text='Ссылка на git-репозиторий проекта', max_length=255, verbose_name='Ссылка на git-репозиторий проекта')),
                ('text', models.TextField(help_text='Описание проекта', verbose_name='Описание проекта')),
            ],
        ),
        migrations.RemoveField(
            model_name='examplespythonheaderorlist2text',
            name='up',
        ),
        migrations.RemoveField(
            model_name='examplespythonheaderorlist3text',
            name='up',
        ),
        migrations.RemoveField(
            model_name='examplespythonheaderorlist4text',
            name='up',
        ),
        migrations.RemoveField(
            model_name='examplespythontext',
            name='up',
        ),
        migrations.DeleteModel(
            name='ExamplesPythonHeaderorList1Text',
        ),
        migrations.DeleteModel(
            name='ExamplesPythonHeaderorList2Text',
        ),
        migrations.DeleteModel(
            name='ExamplesPythonHeaderorList3Text',
        ),
        migrations.DeleteModel(
            name='ExamplesPythonHeaderorList4Text',
        ),
        migrations.DeleteModel(
            name='ExamplesPythonText',
        ),
    ]
