# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_auto_20170515_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplespython',
            old_name='bimage',
            new_name='image',
        ),
    ]
