# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_auto_20170522_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(db_index=True, help_text='Порядковый номер объекта на странице', unique=True, verbose_name='Порядковый номер объекта на странице')),
                ('text', models.TextField(help_text='Описание места учёбы', verbose_name='Описание места учёбы')),
            ],
        ),
        migrations.RemoveField(
            model_name='educationheaderorlist2text',
            name='up',
        ),
        migrations.RemoveField(
            model_name='educationheaderorlist3text',
            name='up',
        ),
        migrations.RemoveField(
            model_name='educationheaderorlist4text',
            name='up',
        ),
        migrations.RemoveField(
            model_name='educationtext',
            name='up',
        ),
        migrations.DeleteModel(
            name='EducationHeaderorList1Text',
        ),
        migrations.DeleteModel(
            name='EducationHeaderorList2Text',
        ),
        migrations.DeleteModel(
            name='EducationHeaderorList3Text',
        ),
        migrations.DeleteModel(
            name='EducationHeaderorList4Text',
        ),
        migrations.DeleteModel(
            name='EducationText',
        ),
    ]
